<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRRxQZkw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRRxQZkw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRRxQZkw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRRxQZkw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRRxQZkw\App_KernelDevDebugContainer([
    'container.build_hash' => 'RRxQZkw',
    'container.build_id' => '4cf9df34',
    'container.build_time' => 1675865345,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRRxQZkw');
