<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRPIOwBE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRPIOwBE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRPIOwBE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRPIOwBE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRPIOwBE\App_KernelDevDebugContainer([
    'container.build_hash' => 'RPIOwBE',
    'container.build_id' => 'dcdb4a0c',
    'container.build_time' => 1678711958,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRPIOwBE');
