<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBxzcMBq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBxzcMBq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBxzcMBq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBxzcMBq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBxzcMBq\App_KernelDevDebugContainer([
    'container.build_hash' => 'BxzcMBq',
    'container.build_id' => 'b80e2a6b',
    'container.build_time' => 1675889526,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBxzcMBq');
