<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_hardwarePlacement_index' => [[], ['_controller' => 'App\\Controller\\HardwarePlacementController::index'], [], [['text', '/api/hardwarePlacement']], [], [], []],
    'api_hardwarePlacement_new' => [[], ['_controller' => 'App\\Controller\\HardwarePlacementController::new'], [], [['text', '/api/hardwarePlacement']], [], [], []],
    'api_hardwarePlacement_show' => [['id'], ['_controller' => 'App\\Controller\\HardwarePlacementController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/hardwarePlacement']], [], [], []],
    'api_hardwarePlacement_edit' => [['id'], ['_controller' => 'App\\Controller\\HardwarePlacementController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/hardwarePlacement']], [], [], []],
    'api_hardwarePlacement_delete' => [['id'], ['_controller' => 'App\\Controller\\HardwarePlacementController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/hardwarePlacement']], [], [], []],
    'api_hardwareUnit_index' => [[], ['_controller' => 'App\\Controller\\HardwareUnitController::index'], [], [['text', '/api/hardwareUnit']], [], [], []],
    'api_hardwareUnit_new' => [[], ['_controller' => 'App\\Controller\\HardwareUnitController::new'], [], [['text', '/api/hardwareUnit']], [], [], []],
    'api_hardwareUnit_show' => [['id'], ['_controller' => 'App\\Controller\\HardwareUnitController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/hardwareUnit']], [], [], []],
    'api_hardwareUnit_edit' => [['id'], ['_controller' => 'App\\Controller\\HardwareUnitController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/hardwareUnit']], [], [], []],
    'api_hardwareUnit_delete' => [['id'], ['_controller' => 'App\\Controller\\HardwareUnitController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/hardwareUnit']], [], [], []],
    'api_hardwareUnitType_index' => [[], ['_controller' => 'App\\Controller\\HardwareUnitTypeController::index'], [], [['text', '/api/hardwareUnitType']], [], [], []],
    'api_hardwareUnitType_new' => [[], ['_controller' => 'App\\Controller\\HardwareUnitTypeController::new'], [], [['text', '/api/hardwareUnitType']], [], [], []],
    'api_hardwareUnitType_show' => [['id'], ['_controller' => 'App\\Controller\\HardwareUnitTypeController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/hardwareUnitType']], [], [], []],
    'api_hardwareUnitType_edit' => [['id'], ['_controller' => 'App\\Controller\\HardwareUnitTypeController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/hardwareUnitType']], [], [], []],
    'api_hardwareUnitType_delete' => [['id'], ['_controller' => 'App\\Controller\\HardwareUnitTypeController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/hardwareUnitType']], [], [], []],
    'api_measurement_index' => [[], ['_controller' => 'App\\Controller\\MeasurementController::index'], [], [['text', '/api/measurement']], [], [], []],
    'api_measurement_new' => [[], ['_controller' => 'App\\Controller\\MeasurementController::new'], [], [['text', '/api/measurement']], [], [], []],
    'api_measurement_show' => [['id'], ['_controller' => 'App\\Controller\\MeasurementController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/measurement']], [], [], []],
    'api_measurement_edit' => [['id'], ['_controller' => 'App\\Controller\\MeasurementController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/measurement']], [], [], []],
    'api_measurement_delete' => [['id'], ['_controller' => 'App\\Controller\\MeasurementController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/measurement']], [], [], []],
    'api_measurementType_index' => [[], ['_controller' => 'App\\Controller\\MeasurementTypeController::index'], [], [['text', '/api/measurementType']], [], [], []],
    'api_measurementType_new' => [[], ['_controller' => 'App\\Controller\\MeasurementTypeController::new'], [], [['text', '/api/measurementType']], [], [], []],
    'api_measurementType_show' => [['id'], ['_controller' => 'App\\Controller\\MeasurementTypeController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/measurementType']], [], [], []],
    'api_measurementType_edit' => [['id'], ['_controller' => 'App\\Controller\\MeasurementTypeController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/measurementType']], [], [], []],
    'api_measurementType_delete' => [['id'], ['_controller' => 'App\\Controller\\MeasurementTypeController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/measurementType']], [], [], []],
];
